# German translations. Keys: English text as it appears on the page (§ = an inline icon).
DE = {
# ---- chrome: header, nav, footer ----
"Skip to content": "Zum Inhalt springen",
"Email us": "E-Mail schreiben",
"Freight & Logistics · Est. 1999": "Spedition & Logistik · Seit 1999",
"Home": "Startseite",
"About": "Über uns",
"Services": "Leistungen",
"Routes": "Routen",
"Gallery": "Galerie",
"Guides": "Ratgeber",
"FAQ": "FAQ",
"Contact": "Kontakt",
"Get a Quote": "Angebot anfordern",
"<span>01</span>Home": "<span>01</span>Startseite",
"<span>02</span>About": "<span>02</span>Über uns",
"<span>03</span>Services": "<span>03</span>Leistungen",
"<span>04</span>Routes": "<span>04</span>Routen",
"<span>05</span>Gallery": "<span>05</span>Galerie",
"<span>06</span>Calculator": "<span>06</span>Kostenrechner",
"<span>07</span>Book a Shipment": "<span>07</span>Sendung buchen",
"<span>08</span>Guides": "<span>08</span>Ratgeber",
"<span>09</span>FAQ": "<span>09</span>FAQ",
"<span>10</span>Contact": "<span>10</span>Kontakt",
"<span>11</span>Get a Quote": "<span>11</span>Angebot anfordern",
"§ Chat on WhatsApp": "§ Per WhatsApp schreiben",
"Call +49 1521 9521826": "Anrufen: +49 1521 9521826",
"Essen, Germany · Lagos, Nigeria": "Essen, Deutschland · Lagos, Nigeria",
"Direct freight forwarding from Germany to destinations worldwide. Honest estimates, fair pricing, clear communication.": "Direkte Spedition von Deutschland zu Zielen weltweit. Ehrliche Kostenschätzungen, faire Preise, klare Kommunikation.",
"Company": "Unternehmen",
"About Us": "Über uns",
"Shipping guides": "Versand-Ratgeber",
"Shipping": "Versand",
"Book Shipment": "Sendung buchen",
"Calculator": "Kostenrechner",
"Offices": "Standorte",
"<strong>Essen</strong><br/>Ripshorster Str. 379<br/>45357 Essen, Germany": "<strong>Essen</strong><br/>Ripshorster Str. 379<br/>45357 Essen, Deutschland",
"<strong>Lagos</strong><br/>Olodi Apapa, Lagos, Nigeria": "<strong>Lagos</strong><br/>Olodi Apapa, Lagos, Nigeria",
"© <span data-year=\"\">2026</span> EL-ROI Shipping Services. All rights reserved.": "© <span data-year=\"\">2026</span> EL-ROI Shipping Services. Alle Rechte vorbehalten.",
"<a href=\"privacy.html\">Privacy Policy</a> · <a href=\"terms.html\">Terms & Conditions</a> · <em>Your satisfaction, our priority.</em>": "<a href=\"privacy.html\">Datenschutz</a> · <a href=\"terms.html\">AGB</a> · <em>Ihre Zufriedenheit ist unsere Priorität.</em>",
"EL-ROI Shipping Services home": "EL-ROI Shipping Services Startseite",
"Primary": "Hauptmenü",
"Language": "Sprache",
"Open menu": "Menü öffnen",
"Mobile": "Mobiles Menü",
"Chat on WhatsApp": "Per WhatsApp schreiben",
"Breadcrumb": "Brotkrumen-Navigation",
"EL-ROI Shipping: Germany to any part of the world": "EL-ROI Shipping: von Deutschland in jeden Teil der Welt",
"/": "/",
# ---- shared CTA + map ----
"Get started": "Jetzt starten",
"Ready to move <em>your cargo?</em>": "Bereit, <em>Ihre Fracht zu versenden?</em>",
"Get a transparent quote, or reach us directly on WhatsApp. The estimate we give you is the price you pay.": "Holen Sie sich ein transparentes Angebot oder schreiben Sie uns direkt per WhatsApp. Der Preis, den wir Ihnen nennen, ist der Preis, den Sie zahlen.",
"Request a Quote §": "Angebot anfordern §",
"Request a Quote": "Angebot anfordern",
"Essen office": "Büro Essen",
"Lagos office": "Büro Lagos",
"Open in Google Maps §": "In Google Maps öffnen §",
"Choose office map": "Standortkarte wählen",
"Map of the EL-ROI office in Essen, Germany": "Karte des EL-ROI-Büros in Essen, Deutschland",
"Map of the EL-ROI office in Olodi Apapa, Lagos": "Karte des EL-ROI-Büros in Olodi Apapa, Lagos",
# ---- image alt texts ----
"Car transporter loaded with two trucks for export": "Autotransporter, beladen mit zwei Lkw für den Export",
"Rear view of a red Volvo FH tractor unit": "Rückansicht einer roten Volvo-FH-Sattelzugmaschine",
"Blue Schmitz container chassis trailer": "Blaues Schmitz-Containerchassis",
"A van loaded inside a shipping container": "Ein Transporter, verladen in einem Seecontainer",
"Loading cargo into an open container": "Fracht wird in einen offenen Container geladen",
"Yellow 40ft shipping container on a trailer": "Gelber 40-Fuß-Seecontainer auf einem Auflieger",
"Rear of a Schmitz tri-axle container chassis": "Heck eines dreiachsigen Schmitz-Containerchassis",
"Green John Deere tractor in a yard, being prepared for shipping": "Grüner John-Deere-Traktor auf dem Hof, bereit für den Versand",
"Inside a shipping container during loading": "Blick in einen Seecontainer während der Beladung",
"Front of a red Volvo FH tractor unit": "Front einer roten Volvo-FH-Sattelzugmaschine",
"John Deere 3140 tractor with front loader": "John-Deere-3140-Traktor mit Frontlader",
"Blue Mercedes-Benz van ready for export": "Blauer Mercedes-Benz-Transporter, bereit für den Export",
"Transporter loaded with a van and a truck for export": "Transporter mit einem Kleintransporter und einem Lkw für den Export",
"Loading engines into a container at night": "Nächtliche Verladung von Motoren in einen Container",
"Red tri-axle container chassis in a yard": "Rotes dreiachsiges Containerchassis auf dem Hof",
"Wrapped cars strapped inside a container during loading": "Verpackte und verzurrte Autos in einem Container während der Beladung",
"Engines and parts packed tightly into a container": "Motoren und Teile, dicht in einen Container gepackt",
"3D globe showing EL-ROI shipping routes from Essen, Germany to Europe and to destinations worldwide: the Americas, Africa, the Middle East and Asia": "3D-Globus mit den EL-ROI-Versandrouten von Essen nach Europa und zu Zielen weltweit: Amerika, Afrika, Naher Osten und Asien",
"Scroll photos left": "Fotos nach links blättern",
"Scroll photos right": "Fotos nach rechts blättern",
"Filter photos": "Fotos filtern",
"Weight slider": "Gewichtsregler",
# ---- structured data ----
"EL-ROI Shipping Services": "EL-ROI Shipping Services",
"Freight forwarder in Essen, Germany since 1999. Sea freight for vehicles, trucks, tractors, 20ft and 40ft containers, machinery and general cargo from Germany to any part of the world, with major routes to Belgium, Austria and Holland and an office in Lagos, Nigeria.": "Spedition in Essen seit 1999. Seefracht für Fahrzeuge, Lkw, Traktoren, 20- und 40-Fuß-Container, Maschinen und Stückgut von Deutschland in jeden Teil der Welt, mit Hauptrouten nach Belgien, Österreich und in die Niederlande und einem Büro in Lagos, Nigeria.",
"Your satisfaction, our priority": "Ihre Zufriedenheit ist unsere Priorität",
"customer service": "Kundenservice",
# ---- 404 ----
"Page not found | EL-ROI Shipping Services": "Seite nicht gefunden | EL-ROI Shipping Services",
"This page could not be found.": "Diese Seite wurde nicht gefunden.",
"Error 404": "Fehler 404",
"This page has <em>gone off route.</em>": "Diese Seite ist <em>vom Kurs abgekommen.</em>",
"The page you're looking for doesn't exist or has moved.": "Die gesuchte Seite existiert nicht oder wurde verschoben.",
"Back to home §": "Zur Startseite §",
"Contact us": "Kontakt aufnehmen",
# ---- about ----
"About Us: Freight Forwarder in Essen since 1999 | EL-ROI Shipping": "Über uns: Spedition in Essen seit 1999 | EL-ROI Shipping",
"EL-ROI Shipping Services: a German freight forwarder in Essen with an office in Lagos. Over 20 years of honest estimates, fair pricing and clear communication.": "EL-ROI Shipping Services: eine deutsche Spedition in Essen mit Büro in Lagos. Über 20 Jahre ehrliche Kostenschätzungen, faire Preise und klare Kommunikation.",
"Our story": "Unsere Geschichte",
"20+ years of <em>honest freight forwarding</em>": "Über 20 Jahre <em>ehrliche Spedition</em>",
"A German shipping company built on relationships: honest estimates, fair pricing and clear communication at every step.": "Ein deutsches Versandunternehmen, das auf Beziehungen baut: ehrliche Kostenschätzungen, faire Preise und klare Kommunikation bei jedem Schritt.",
"Who we are": "Wer wir sind",
"A German shipping company <em>built on relationships</em>": "Ein deutsches Versandunternehmen, <em>das auf Beziehungen baut</em>",
"We're a German-based shipping service, in operation for over 20 years, moving cargo directly from Germany to any part of the world.": "Wir sind ein Versanddienstleister mit Sitz in Deutschland und seit über 20 Jahren im Geschäft. Wir bringen Fracht direkt von Deutschland in jeden Teil der Welt.",
"From global export of tractors, trucks, 40FT/20FT containers, vehicles and parts, to construction equipment and engines, we've built our name on doing the job right.": "Vom weltweiten Export von Traktoren, Lkw, 40- und 20-Fuß-Containern, Fahrzeugen und Teilen bis zu Baumaschinen und Motoren: Unseren Namen haben wir uns durch zuverlässige Arbeit gemacht.",
"We believe great service starts with great relationships. That means honest estimates, fair pricing, and clear communication every step of the way.": "Guter Service beginnt mit guten Beziehungen. Das heißt: ehrliche Kostenschätzungen, faire Preise und klare Kommunikation bei jedem Schritt.",
"At a glance": "Auf einen Blick",
"Founded": "Gegründet",
"Headquarters": "Hauptsitz",
"Ripshorster Str. 379, 45357 Essen, Germany": "Ripshorster Str. 379, 45357 Essen, Deutschland",
"Second office": "Zweites Büro",
"Management": "Geschäftsleitung",
"Major routes": "Hauptrouten",
"Germany to Belgium, Austria and Holland": "Deutschland nach Belgien, Österreich und in die Niederlande",
"Sea freight, Germany to worldwide": "Seefracht, von Deutschland weltweit",
"Transit": "Laufzeit",
"Around two weeks after loading (average)": "Rund zwei Wochen nach der Verladung (Durchschnitt)",
"Core values": "Unsere Werte",
"Honesty.": "Ehrlichkeit.",
"Fairness.": "Fairness.",
"Reliability.": "Zuverlässigkeit.",
"Easy shipment.": "Einfacher Versand.",
"Vision": "Vision",
"Your satisfaction is our priority": "Ihre Zufriedenheit ist unsere Priorität",
"We're there with you every step of the way, giving you a fast and reliable shipping experience.": "Wir begleiten Sie bei jedem Schritt und sorgen für einen schnellen und zuverlässigen Versand.",
"Mission": "Mission",
"Total transparency": "Volle Transparenz",
"Before any job starts, you get a detailed estimate so you can make the right decision for your shipment. No hidden fees, no pressure.": "Bevor ein Auftrag beginnt, erhalten Sie eine detaillierte Kostenschätzung, damit Sie die richtige Entscheidung treffen können. Keine versteckten Gebühren, kein Druck.",
"Every job, every time": "Bei jedem Auftrag",
"Honesty, fairness, reliability and easy shipment. Every job, every time.": "Ehrlichkeit, Fairness, Zuverlässigkeit und einfacher Versand. Bei jedem Auftrag, jedes Mal.",
"On the ground": "Vor Ort",
"The work <em>speaks</em>": "Unsere Arbeit <em>spricht für sich</em>",
"View gallery §": "Zur Galerie §",
# ---- guides listing ----
"Shipping Guides & News | EL-ROI Shipping": "Versand-Ratgeber & News | EL-ROI Shipping",
"Practical guides to shipping from Germany: shipping a car to Nigeria, Form M, 20ft vs 40ft containers and what to prepare before booking.": "Praktische Ratgeber zum Versand aus Deutschland: Auto nach Nigeria verschiffen, Form M, 20- oder 40-Fuß-Container und was Sie vor der Buchung vorbereiten sollten.",
"Guides & news": "Ratgeber & News",
"Shipping guides <em>& news</em>": "Versand-Ratgeber <em>& News</em>",
"Practical, plain-English guides to shipping from Germany, and updates from EL-ROI Shipping Services.": "Praktische Ratgeber zum Versand aus Deutschland (auf Englisch) und Neuigkeiten von EL-ROI Shipping Services.",
"Know before <em>you ship</em>": "Gut informiert <em>verschiffen</em>",
"Vehicles · 5 min read": "Fahrzeuge · 5 Min. Lesezeit · Englisch",
"How to ship a car from Germany to Nigeria": "Auto von Deutschland nach Nigeria verschiffen",
"Step-by-step guide to shipping a car from Germany to Lagos, Nigeria: documents, Form M, container shipping, transit time and customs clearance.": "Schritt für Schritt: ein Auto von Deutschland nach Lagos verschiffen. Dokumente, Form M, Containerversand, Laufzeit und Verzollung.",
"Read the guide §": "Ratgeber lesen §",
"Documents · 4 min read": "Dokumente · 4 Min. Lesezeit · Englisch",
"What is Form M? A simple guide for shipping to Nigeria": "Was ist Form M? Einfach erklärt für den Versand nach Nigeria",
"Form M explained in plain English: what it is, who completes it, when it must be done and which documents your bank in Nigeria needs before shipping.": "Form M einfach erklärt: was es ist, wer es ausfüllt, wann es fertig sein muss und welche Unterlagen die Bank in Nigeria vor dem Versand braucht.",
"Containers · 4 min read": "Container · 4 Min. Lesezeit · Englisch",
"20ft vs 40ft container: which size do you need?": "20- oder 40-Fuß-Container: Welche Größe brauchen Sie?",
"Compare 20ft, 40ft and 40ft high cube shipping containers: inside dimensions, volume and payload, how many cars fit, and which size suits your cargo.": "20-Fuß-, 40-Fuß- und 40-Fuß-High-Cube-Container im Vergleich: Innenmaße, Volumen, Zuladung, wie viele Autos hineinpassen und welche Größe zu Ihrer Fracht passt.",
"Checklist · 3 min read": "Checkliste · 3 Min. Lesezeit · Englisch",
"What to prepare before booking a shipment": "Was Sie vor der Buchung vorbereiten sollten",
"A checklist of the details and documents to have ready before booking sea freight from Germany, so your shipment moves without delays.": "Eine Checkliste der Angaben und Dokumente, die Sie vor der Buchung von Seefracht aus Deutschland bereithalten sollten, damit Ihre Sendung ohne Verzögerung läuft.",
"Company news": "Neuigkeiten",
"From <em>EL-ROI</em>": "Von <em>EL-ROI</em>",
"Welcome to our new website": "Willkommen auf unserer neuen Website",
"Our new online home makes it easier to request quotes, book shipments and reach our team in Essen and Lagos.": "Auf unserer neuen Website können Sie noch einfacher Angebote anfordern, Sendungen buchen und unser Team in Essen und Lagos erreichen.",
"Over 20 years of shipping, and counting": "Über 20 Jahre Versand, und es geht weiter",
"Since 1999 we have been moving vehicles, containers and heavy cargo from Germany to the world.": "Seit 1999 bringen wir Fahrzeuge, Container und Schwerfracht von Deutschland in die Welt.",
# ---- booking ----
"Book a Shipment from Germany | EL-ROI Shipping": "Sendung aus Deutschland buchen | EL-ROI Shipping",
"Book sea freight from Germany to Europe, Lagos or anywhere in the world. Send your cargo details and we confirm availability and next steps.": "Buchen Sie Seefracht von Deutschland nach Europa, Lagos oder weltweit. Senden Sie uns Ihre Frachtdaten, und wir bestätigen Verfügbarkeit und nächste Schritte.",
"Book a Shipment": "Sendung buchen",
"Book a shipment": "Sendung buchen",
"Start your <em>shipment booking</em>": "Starten Sie <em>Ihre Buchung</em>",
"Provide your shipment details below. Our team will confirm availability and next steps by phone or email.": "Geben Sie unten die Details Ihrer Sendung ein. Unser Team bestätigt Verfügbarkeit und nächste Schritte telefonisch oder per E-Mail.",
"Booking request": "Buchungsanfrage",
"Fields marked <b style=\"color:var(--gold-deep)\">*</b> are required.": "Mit <b style=\"color:var(--gold-deep)\">*</b> markierte Felder sind Pflichtfelder.",
"Full name <b>*</b>": "Vollständiger Name <b>*</b>",
"Phone number <b>*</b>": "Telefonnummer <b>*</b>",
"Email address <b>*</b>": "E-Mail-Adresse <b>*</b>",
"Company or private name": "Firmen- oder Privatname",
"Address <b>*</b>": "Adresse <b>*</b>",
"Pickup location <b>*</b>": "Abholort <b>*</b>",
"Destination <b>*</b>": "Zielort <b>*</b>",
"Cargo type <b>*</b>": "Frachtart <b>*</b>",
"Select cargo type": "Frachtart wählen",
"General Cargo": "Stückgut",
"Containers": "Container",
"Vehicles": "Fahrzeuge",
"Fragile Goods": "Zerbrechliche Güter",
"Oversized / Heavy Cargo": "Übergroße / schwere Fracht",
"Machinery / Equipment": "Maschinen / Ausrüstung",
"Documents": "Dokumente",
"Cargo weight (kg)": "Frachtgewicht (kg)",
"Number of packages": "Anzahl der Packstücke",
"Preferred shipping method": "Bevorzugte Versandart",
"Sea Freight": "Seefracht",
"Vehicle document / special declaration reference (if applicable)": "Fahrzeugpapiere / Referenz der Sondererklärung (falls zutreffend)",
"Include your Form M reference if your cargo needs a special declaration.": "Geben Sie Ihre Form-M-Referenz an, wenn Ihre Fracht eine Sondererklärung benötigt.",
"Upload cargo / shipping documents (optional)": "Fracht- / Versanddokumente hochladen (optional)",
"PDF, JPG or PNG. Never upload bank details, passwords or payment credentials here.": "PDF, JPG oder PNG. Laden Sie hier niemals Bankdaten, Passwörter oder Zahlungsdaten hoch.",
"A booking request doesn't commit you to anything. We confirm the details with you first. See our <a href=\"privacy.html\">Privacy Policy</a>. Bookings are subject to our <a href=\"terms.html\">Terms & Conditions</a>.": "Eine Buchungsanfrage verpflichtet Sie zu nichts. Wir stimmen die Details zuerst mit Ihnen ab. Siehe unsere <a href=\"privacy.html\">Datenschutzerklärung</a>. Für Buchungen gelten unsere <a href=\"terms.html\">AGB</a>.",
"Submit Booking Request §": "Buchungsanfrage senden §",
"What happens next": "So geht es weiter",
"We review your details": "Wir prüfen Ihre Angaben",
"Our team checks your cargo, route and paperwork needs.": "Unser Team prüft Fracht, Route und benötigte Unterlagen.",
"You get a clear estimate": "Sie erhalten eine klare Kostenschätzung",
"The full cost up front, with no hidden fees added later.": "Alle Kosten vorab, ohne versteckte Gebühren im Nachhinein.",
"You decide": "Sie entscheiden",
"No pressure. Book only when you're ready.": "Kein Druck. Buchen Sie erst, wenn Sie bereit sind.",
"Prefer to talk?": "Lieber persönlich?",
"Call or WhatsApp": "Anruf oder WhatsApp",
"§Chat on WhatsApp": "§Per WhatsApp schreiben",
"Hello EL-ROI, I'd like to book a shipment:": "Hallo EL-ROI, ich möchte eine Sendung buchen:",
"Book a Shipment from Germany": "Sendung aus Deutschland buchen",
# ---- calculator ----
"Shipping Cost Calculator: Germany to Europe, Lagos & Worldwide | EL-ROI": "Versandkostenrechner: Deutschland nach Europa, Lagos & weltweit | EL-ROI",
"Estimate the cost of shipping from Germany by cargo type, weight and destination. Then request a formal quote for the exact price.": "Schätzen Sie die Versandkosten ab Deutschland nach Frachtart, Gewicht und Ziel. Den genauen Preis erhalten Sie mit einem verbindlichen Angebot.",
"Estimate": "Kostenschätzung",
"Shipping cost <em>calculator</em>": "Versandkosten<em>rechner</em>",
"Get a rough estimate based on cargo type, weight and destination. Final pricing is confirmed through a formal quote.": "Erhalten Sie eine grobe Schätzung nach Frachtart, Gewicht und Ziel. Der endgültige Preis wird mit einem verbindlichen Angebot bestätigt.",
"<i>01</i> Cargo type": "<i>01</i> Frachtart",
"Estimated weight": "Geschätztes Gewicht",
"Pallet ~500 kg": "Palette ~500 kg",
"Car ~1,500 kg": "Auto ~1.500 kg",
"Tractor ~5,000 kg": "Traktor ~5.000 kg",
"Truck ~7,500 kg": "Lkw ~7.500 kg",
"<i>03</i> Destination": "<i>03</i> Ziel",
"Europe (Belgium, Austria, Holland)": "Europa (Belgien, Österreich, Niederlande)",
"Rest of World": "Rest der Welt",
"Estimated cost": "Geschätzte Kosten",
"€ —": "— €",
"Base rate": "Grundpreis",
"Chargeable weight": "Abrechnungsgewicht",
"Route factor": "Routenfaktor",
"This is a rough estimate only and does not reflect final pricing. Request a formal quote for accurate costs.": "Dies ist nur eine grobe Schätzung und kein Endpreis. Fordern Sie für genaue Kosten ein verbindliches Angebot an.",
"Request a formal quote §": "Verbindliches Angebot anfordern §",
"Shipping Cost Calculator": "Versandkostenrechner",
# ---- contact ----
"Contact EL-ROI Shipping | Essen, Germany & Lagos, Nigeria": "Kontakt EL-ROI Shipping | Essen, Deutschland & Lagos, Nigeria",
"Contact EL-ROI Shipping Services: Ripshorster Str. 379, 45357 Essen, and Olodi Apapa, Lagos. Call +49 1521 9521826 or chat on WhatsApp.": "Kontakt zu EL-ROI Shipping Services: Ripshorster Str. 379, 45357 Essen, und Olodi Apapa, Lagos. Rufen Sie +49 1521 9521826 an oder schreiben Sie per WhatsApp.",
"Get in touch": "Kontakt",
"Contact <em>EL-ROI Shipping</em>": "Kontakt zu <em>EL-ROI Shipping</em>",
"Send a message, call, or chat with us on WhatsApp.": "Schreiben Sie uns, rufen Sie an oder chatten Sie mit uns per WhatsApp.",
"Send us a message": "Nachricht senden",
"We'll get back to you by email or phone.": "Wir melden uns per E-Mail oder Telefon bei Ihnen.",
"Phone number": "Telefonnummer",
"Message <b>*</b>": "Nachricht <b>*</b>",
"Never send bank details or passwords through this form. See our <a href=\"privacy.html\">Privacy Policy</a>. Bookings are subject to our <a href=\"terms.html\">Terms & Conditions</a>.": "Senden Sie über dieses Formular niemals Bankdaten oder Passwörter. Siehe unsere <a href=\"privacy.html\">Datenschutzerklärung</a>. Für Buchungen gelten unsere <a href=\"terms.html\">AGB</a>.",
"Send Message §": "Nachricht senden §",
"Essen, Germany": "Essen, Deutschland",
"Ripshorster Str. 379<br/>45357 Essen, Germany": "Ripshorster Str. 379<br/>45357 Essen, Deutschland",
"Nigeria office": "Büro Nigeria",
"Prefer WhatsApp?": "Lieber WhatsApp?",
"Message us with your cargo and destination.": "Schreiben Sie uns Ihre Fracht und Ihr Ziel.",
"Hello EL-ROI, message from your website:": "Hallo EL-ROI, Nachricht über Ihre Website:",
"What are you shipping, and where to?": "Was möchten Sie versenden, und wohin?",
"Contact EL-ROI Shipping": "Kontakt EL-ROI Shipping",
# ---- FAQ ----
"Shipping FAQ: Transit Times, Form M, Customs & Documents | EL-ROI": "Versand-FAQ: Laufzeiten, Form M, Zoll & Dokumente | EL-ROI",
"Answers about shipping from Germany: transit times, cargo types, documents, Form M, customs duties, insurance, container sizes and our offices.": "Antworten zum Versand aus Deutschland: Laufzeiten, Frachtarten, Dokumente, Form M, Zölle, Versicherung, Containergrößen und unsere Standorte.",
"Support": "Hilfe",
"Frequently asked <em>questions</em>": "Häufige <em>Fragen</em>",
"Clear answers to the questions we hear most.": "Klare Antworten auf die Fragen, die wir am häufigsten hören.",
"Still have a question?": "Noch Fragen?",
"Talk to a real person": "Sprechen Sie mit einem Menschen",
"You deal with people who know your shipment, not a call centre queue.": "Sie sprechen mit Menschen, die Ihre Sendung kennen, nicht mit einer Callcenter-Warteschleife.",
"§Email us": "§E-Mail schreiben",
"Do you only ship to Nigeria?": "Versenden Sie nur nach Nigeria?",
"No. We ship from Germany to any part of the world by sea freight. Our major routes are to Belgium, Austria and Holland, and we have our own office in Lagos, Nigeria.": "Nein. Wir versenden per Seefracht von Deutschland in jeden Teil der Welt. Unsere Hauptrouten führen nach Belgien, Österreich und in die Niederlande, und wir haben ein eigenes Büro in Lagos, Nigeria.",
"Can you ship a car from Germany to Nigeria?": "Können Sie ein Auto von Deutschland nach Nigeria verschiffen?",
"Yes. Cars, vans, trucks and tractors are some of the most common things we ship. See our <a href=\"guide-ship-car-germany-to-nigeria.html\">step-by-step guide to shipping a car to Nigeria</a>.": "Ja. Autos, Transporter, Lkw und Traktoren gehören zu dem, was wir am häufigsten verschiffen. Siehe unseren <a href=\"guide-ship-car-germany-to-nigeria.html\">Schritt-für-Schritt-Ratgeber (Englisch)</a>.",
"Yes. Cars, vans, trucks and tractors are some of the most common things we ship. See our step-by-step guide to shipping a car to Nigeria.": "Ja. Autos, Transporter, Lkw und Traktoren gehören zu dem, was wir am häufigsten verschiffen. Siehe unseren Schritt-für-Schritt-Ratgeber.",
"What container sizes do you use?": "Welche Containergrößen nutzen Sie?",
"20ft and 40ft containers, including 40ft high cube. See <a href=\"guide-20ft-vs-40ft-container.html\">20ft vs 40ft containers</a> to find the right size.": "20- und 40-Fuß-Container, auch 40-Fuß-High-Cube. Die passende Größe finden Sie in unserem Vergleich <a href=\"guide-20ft-vs-40ft-container.html\">20 oder 40 Fuß (Englisch)</a>.",
"20ft and 40ft containers, including 40ft high cube. See 20ft vs 40ft containers to find the right size.": "20- und 40-Fuß-Container, auch 40-Fuß-High-Cube. Die passende Größe finden Sie in unserem Containervergleich.",
"How long does shipping take?": "Wie lange dauert der Versand?",
"Delivery time depends on the destination country, but on average it takes around two weeks after your container is loaded onto the ship.": "Die Laufzeit hängt vom Zielland ab, liegt aber im Durchschnitt bei rund zwei Wochen, nachdem Ihr Container auf das Schiff verladen wurde.",
"What cargo types do you handle?": "Welche Frachtarten übernehmen Sie?",
"We handle general cargo, containers, vehicles, fragile goods, oversized and heavy cargo, machinery and equipment, and documents.": "Wir übernehmen Stückgut, Container, Fahrzeuge, zerbrechliche Güter, übergroße und schwere Fracht, Maschinen und Ausrüstung sowie Dokumente.",
"What information do I need to book a shipment?": "Welche Angaben brauche ich für eine Buchung?",
"Your full name, phone number, email, pickup location, destination, cargo type, cargo weight, number of packages, and preferred shipping method.": "Ihren vollständigen Namen, Telefonnummer, E-Mail, Abholort, Ziel, Frachtart, Frachtgewicht, Anzahl der Packstücke und die bevorzugte Versandart.",
"Do you offer shipment tracking?": "Bieten Sie Sendungsverfolgung an?",
"Shipment tracking is coming soon. In the meantime, our team will keep you updated directly on your shipment status.": "Die Sendungsverfolgung kommt bald. Bis dahin hält unser Team Sie direkt über den Status Ihrer Sendung auf dem Laufenden.",
"What documents are needed for special declarations?": "Welche Dokumente sind für Sondererklärungen nötig?",
"Certain cargo, like vehicles, requires vehicle documentation and may need a Form M special declaration. We'll guide you through what's required for your shipment. See <a href=\"guide-form-m-nigeria.html\">What is Form M?</a>": "Bestimmte Fracht, etwa Fahrzeuge, benötigt Fahrzeugpapiere und eventuell eine Sondererklärung (Form M). Wir erklären Ihnen, was für Ihre Sendung nötig ist. Siehe <a href=\"guide-form-m-nigeria.html\">Was ist Form M? (Englisch)</a>",
"Certain cargo, like vehicles, requires vehicle documentation and may need a Form M special declaration. We'll guide you through what's required for your shipment. See What is Form M?": "Bestimmte Fracht, etwa Fahrzeuge, benötigt Fahrzeugpapiere und eventuell eine Sondererklärung (Form M). Wir erklären Ihnen, was für Ihre Sendung nötig ist.",
"Who pays customs duties and import taxes?": "Wer zahlt Zölle und Einfuhrsteuern?",
"Customs duties, import taxes and port charges at the destination are paid by the receiver or importer. They are not included in our freight price unless we agree otherwise in writing.": "Zölle, Einfuhrsteuern und Hafengebühren am Zielort zahlt der Empfänger bzw. Importeur. Sie sind nicht in unserem Frachtpreis enthalten, sofern nichts anderes schriftlich vereinbart ist.",
"Is my cargo insured?": "Ist meine Fracht versichert?",
"Our liability is limited by law, which can be less than the value of your cargo, so we recommend cargo insurance. We can arrange it on request.": "Unsere Haftung ist gesetzlich begrenzt und kann unter dem Wert Ihrer Fracht liegen. Wir empfehlen daher eine Transportversicherung, die wir auf Wunsch vermitteln.",
"Where are your offices?": "Wo sind Ihre Standorte?",
"Our headquarters is at Ripshorster Str. 379, 45357 Essen, Germany, and our second office is in Olodi Apapa, Lagos, Nigeria.": "Unser Hauptsitz ist in der Ripshorster Str. 379, 45357 Essen, und unser zweites Büro befindet sich in Olodi Apapa, Lagos, Nigeria.",
"Can I pay through the website?": "Kann ich über die Website bezahlen?",
"Online payment is coming soon. For now, payment details are arranged directly with our team, never submitted through the website form.": "Online-Zahlung kommt bald. Bis dahin werden Zahlungsdetails direkt mit unserem Team abgestimmt und niemals über das Website-Formular übermittelt.",
"Shipping FAQ": "Versand-FAQ",
# ---- gallery ----
"Gallery: Vehicles, Trucks & Containers We Ship | EL-ROI Shipping": "Galerie: Fahrzeuge, Lkw & Container, die wir verschiffen | EL-ROI Shipping",
"Real photos of cars, trucks, tractors, containers and engines loaded and shipped by EL-ROI Shipping Services from Germany.": "Echte Fotos von Autos, Lkw, Traktoren, Containern und Motoren, die EL-ROI Shipping Services aus Deutschland verladen und verschifft hat.",
"From <em>the yard</em>": "Von unserem <em>Hof</em>",
"Real cargo, real photos: tractors, trucks, trailers and containers on their way from Germany.": "Echte Fracht, echte Fotos: Traktoren, Lkw, Auflieger und Container auf dem Weg aus Deutschland.",
"All": "Alle",
"Trucks & vehicles": "Lkw & Fahrzeuge",
"Tractors & machinery": "Traktoren & Maschinen",
"Containers & trailers": "Container & Auflieger",
"Vehicle transport": "Fahrzeugtransport",
"Trucks loaded for the port": "Lkw, beladen für den Hafen",
"Volvo FH tractor unit": "Volvo-FH-Sattelzugmaschine",
"Trucks": "Lkw",
"John Deere tractor": "John-Deere-Traktor",
"Farm machinery": "Landmaschinen",
"Blue container chassis": "Blaues Containerchassis",
"Trailers": "Auflieger",
"Loading day": "Verladetag",
"Inside the container": "Im Container",
"40ft container": "40-Fuß-Container",
"Ready for the port": "Bereit für den Hafen",
"Tractor unit": "Sattelzugmaschine",
"Tractor with front loader": "Traktor mit Frontlader",
"Tri-axle chassis": "Dreiachs-Chassis",
"Mercedes-Benz van": "Mercedes-Benz-Transporter",
"Vans & light vehicles": "Transporter & leichte Fahrzeuge",
"Loaded for export": "Beladen für den Export",
"Van and truck on a transporter": "Transporter und Lkw auf einem Autotransporter",
"Van in a container": "Transporter im Container",
"Packed for sea freight": "Verpackt für die Seefracht",
"Loading the container": "Container wird beladen",
"Cargo going in": "Die Fracht wird eingeladen",
"Engines": "Motoren",
"Loaded at night": "Nachts verladen",
"Red container chassis": "Rotes Containerchassis",
"Cars in a container": "Autos im Container",
"Wrapped and strapped": "Verpackt und verzurrt",
"Engines & parts": "Motoren & Teile",
"Packed to the roof": "Bis unters Dach gepackt",
"Container chassis": "Containerchassis",
"Have cargo to ship? <em>Send us a photo.</em>": "Fracht zu versenden? <em>Schicken Sie uns ein Foto.</em>",
"Send a photo of your cargo and its destination on WhatsApp, and we'll tell you what it takes to ship it.": "Schicken Sie uns per WhatsApp ein Foto Ihrer Fracht und das Ziel, und wir sagen Ihnen, was für den Versand nötig ist.",
"§ Send on WhatsApp": "§ Per WhatsApp senden",
# ---- home ----
"Shipping from Germany to Nigeria & Worldwide | EL-ROI Shipping, Essen": "Spedition Essen: Seefracht nach Nigeria & weltweit | EL-ROI Shipping",
"Freight forwarder in Essen since 1999. Sea freight for cars, trucks, tractors, containers and machinery from Germany to Europe, Lagos and any part of the world. Honest quotes.": "Spedition in Essen seit 1999. Seefracht für Autos, Lkw, Traktoren, Container und Maschinen von Deutschland nach Europa, Lagos und in jeden Teil der Welt. Ehrliche Angebote.",
"Germany → Worldwide freight forwarding": "Spedition · Deutschland → Weltweit",
"Your cargo,": "Ihre Fracht,",
"moved with": "verschifft mit",
"total transparency.": "voller Transparenz.",
"EL-ROI Shipping Services has connected Germany to the world for over 20 years. Sea freight, vehicles, containers and heavy cargo, handled with honest estimates and clear communication at every step.": "EL-ROI Shipping Services verbindet Deutschland seit über 20 Jahren mit der Welt. Seefracht, Fahrzeuge, Container und Schwerfracht, mit ehrlichen Kostenschätzungen und klarer Kommunikation bei jedem Schritt.",
"§ Or chat with us on WhatsApp": "§ Oder schreiben Sie uns per WhatsApp",
"<i></i>Major routes: Europe": "<i></i>Hauptrouten: Europa",
"<i class=\"eu\"></i>Worldwide destinations": "<i class=\"eu\"></i>Ziele weltweit",
"Drag the globe to spin it": "Ziehen Sie den Globus, um ihn zu drehen",
"Years in operation": "Jahre im Geschäft",
"Established": "Gegründet",
"Offices: Essen & Lagos": "Büros: Essen & Lagos",
"~2<small>wks</small>": "~2<small>Wo.</small>",
"Average transit": "Durchschnittliche Laufzeit",
"Worldwide shipping": "Weltweiter Versand",
"Sea freight specialists": "Seefracht-Spezialisten",
"Vehicles & heavy cargo": "Fahrzeuge & Schwerfracht",
"Germany to the world": "Deutschland in die Welt",
"Since 1999": "Seit 1999",
"What we handle": "Was wir übernehmen",
"Cargo types <em>we move</em>": "Frachtarten, <em>die wir bewegen</em>",
"From single documents to full oversized machinery, every shipment gets the same standard of care.": "Vom einzelnen Dokument bis zur übergroßen Maschine: Jede Sendung erhält dieselbe Sorgfalt.",
"All services §": "Alle Leistungen §",
"01 · Vehicles": "01 · Fahrzeuge",
"Vehicles & parts": "Fahrzeuge & Teile",
"Cars, trucks and vehicle parts shipped with full documentation support.": "Autos, Lkw und Fahrzeugteile, verschifft mit vollständiger Unterstützung bei den Papieren.",
"02 · Agriculture": "02 · Landwirtschaft",
"Tractors & farm machinery": "Traktoren & Landmaschinen",
"Tractors and agricultural equipment, secured for sea freight.": "Traktoren und landwirtschaftliche Geräte, gesichert für die Seefracht.",
"03 · Trucks": "03 · Lkw",
"Trucks & tractor units": "Lkw & Sattelzugmaschinen",
"Tractor heads and commercial vehicles, exported from Germany.": "Zugmaschinen und Nutzfahrzeuge, exportiert aus Deutschland.",
"04 · Heavy": "04 · Schwerlast",
"Oversized & machinery": "Übergroß & Maschinen",
"Trailers, construction equipment and engines, handled with specialist care.": "Auflieger, Baumaschinen und Motoren, mit besonderer Sorgfalt behandelt.",
"Also shipping": "Außerdem",
"General cargo": "Stückgut",
"20FT / 40FT containers": "20-/40-Fuß-Container",
"Machinery & engines": "Maschinen & Motoren",
"Fragile goods": "Zerbrechliche Güter",
"Sea freight": "Seefracht",
"Origin": "Start",
"Germany": "Deutschland",
"~2 weeks": "~2 Wochen",
"Destination": "Ziel",
"Europe": "Europa",
"Belgium · Austria · Holland": "Belgien · Österreich · Niederlande",
"Any part of the world": "Jeder Teil der Welt",
"Our 2nd office": "Unser 2. Büro",
"Global coverage": "Weltweit",
"Wherever your cargo <em>needs to go</em>": "Wohin Ihre Fracht <em>auch muss</em>",
"We ship from Germany to any part of the world, with major routes to Belgium, Austria and Holland and our own office in Lagos. Whatever the route, the same standard of care and communication applies.": "Wir versenden von Deutschland in jeden Teil der Welt, mit Hauptrouten nach Belgien, Österreich und in die Niederlande und einem eigenen Büro in Lagos. Auf jeder Route gelten dieselbe Sorgfalt und Kommunikation.",
"Method": "Versandart",
"Typical transit": "Übliche Laufzeit",
"Europe<small>Belgium · Austria · Holland</small>": "Europa<small>Belgien · Österreich · Niederlande</small>",
"~2 weeks after loading": "~2 Wochen nach Verladung",
"Major route": "Hauptroute",
"Worldwide<small>Africa · Americas · Middle East · Asia</small>": "Weltweit<small>Afrika · Amerika · Naher Osten · Asien</small>",
"Varies by destination": "Je nach Ziel",
"Any port": "Jeder Hafen",
"Lagos, Nigeria<small>Our second office, Olodi Apapa</small>": "Lagos, Nigeria<small>Unser zweites Büro, Olodi Apapa</small>",
"Varies by schedule": "Je nach Fahrplan",
"Local office": "Eigenes Büro",
"All routes depart from Essen, Germany. Transit times are estimates and depend on port schedules, customs and cargo type.": "Alle Routen starten in Essen. Die Laufzeiten sind Schätzungen und hängen von Hafenfahrplänen, Zoll und Frachtart ab.",
"How it works": "So funktioniert es",
"Four steps, <em>no surprises</em>": "Vier Schritte, <em>keine Überraschungen</em>",
"Shipment status": "Sendungsstatus",
"Quote requested": "Angebot angefragt",
"Tell us what you're shipping": "Sagen Sie uns, was Sie versenden",
"Share your cargo details and destination through our quote or booking form.": "Teilen Sie uns Frachtdetails und Ziel über das Angebots- oder Buchungsformular mit.",
"Get a transparent estimate": "Transparente Kostenschätzung",
"We confirm pricing and documentation needs before anything is booked. No hidden fees.": "Wir bestätigen Preis und benötigte Unterlagen, bevor gebucht wird. Keine versteckten Gebühren.",
"Cargo is loaded and shipped": "Verladung und Versand",
"Your shipment moves by sea freight, with any special declarations (Form M) handled for you.": "Ihre Sendung reist per Seefracht, Sondererklärungen (Form M) erledigen wir für Sie.",
"Arrival, typically ~2 weeks": "Ankunft, meist nach ~2 Wochen",
"Delivery time varies by destination, but averages around two weeks after loading.": "Die Laufzeit hängt vom Ziel ab, liegt aber im Schnitt bei rund zwei Wochen nach der Verladung.",
"Your satisfaction is <em>our priority.</em>": "Ihre Zufriedenheit ist <em>unsere Priorität.</em>",
"The EL-ROI promise · since 1999": "Das EL-ROI-Versprechen · seit 1999",
"Why EL-ROI": "Warum EL-ROI",
"Built on relationships, <em>not just routes</em>": "Wir bauen auf Beziehungen, <em>nicht nur auf Routen</em>",
"Five things that make the difference between a shipment that goes smoothly and one that doesn't.": "Fünf Dinge, die den Unterschied machen zwischen einer Sendung, die reibungslos läuft, und einer, die es nicht tut.",
"Transparent estimates": "Transparente Kostenschätzungen",
"You see the full cost before anything is booked. No hidden fees added later.": "Sie sehen alle Kosten, bevor gebucht wird. Keine versteckten Gebühren im Nachhinein.",
"Documentation handled for you": "Wir kümmern uns um die Papiere",
"Vehicle documents, Form M declarations: we guide you through what's required.": "Fahrzeugpapiere, Form-M-Erklärungen: Wir führen Sie durch alles Nötige.",
"Fair, honest pricing": "Faire, ehrliche Preise",
"The estimate we give you is the price you pay, not a starting offer.": "Die Kostenschätzung, die Sie von uns bekommen, ist der Preis, den Sie zahlen, kein Lockangebot.",
"Direct communication": "Direkte Kommunikation",
"You deal with real people who know your shipment, not a call centre queue.": "Sie sprechen mit Menschen, die Ihre Sendung kennen, nicht mit einer Callcenter-Warteschleife.",
"20+ years of experience": "Über 20 Jahre Erfahrung",
"We've been moving cargo from Germany to the world since 1999.": "Seit 1999 bringen wir Fracht von Deutschland in die Welt.",
"Testimonials": "Kundenstimmen",
"What <em>clients say</em>": "Was <em>unsere Kunden sagen</em>",
"“Honest estimate, no surprises at the end. That's rare in freight.”": "„Ehrliche Kostenschätzung, keine Überraschungen am Ende. Das ist selten in der Frachtbranche.“",
"Client name, Company": "Kundenname, Firma",
"“They handled our Form M paperwork without us having to chase anyone.”": "„Sie haben sich um unsere Form-M-Papiere gekümmert, ohne dass wir irgendwem hinterherlaufen mussten.“",
"From the yard": "Von unserem Hof",
"Real cargo, <em>real photos</em>": "Echte Fracht, <em>echte Fotos</em>",
"Full gallery §": "Zur Galerie §",
# ---- privacy ----
"Privacy Policy | EL-ROI Shipping Services": "Datenschutzerklärung | EL-ROI Shipping Services",
"How EL-ROI Shipping Services collects, uses and protects your personal data.": "Wie EL-ROI Shipping Services Ihre personenbezogenen Daten erhebt, nutzt und schützt.",
"Privacy Policy": "Datenschutzerklärung",
"Legal": "Rechtliches",
"Privacy <em>policy</em>": "Datenschutz<em>erklärung</em>",
"On this page": "Auf dieser Seite",
"Who we are": "Wer wir sind",
"What we collect": "Welche Daten wir erheben",
"Why we use it": "Wofür wir sie nutzen",
"Who we share it with": "An wen wir sie weitergeben",
"How long we keep it": "Wie lange wir sie speichern",
"Your rights": "Ihre Rechte",
"Cookies": "Cookies",
"Changes": "Änderungen",
"This website is operated by <strong>EL-ROI Shipping Services</strong>, Ripshorster Str. 379, 45357 Essen, Germany (the “controller” under the EU General Data Protection Regulation, GDPR). We also have an office in Olodi Apapa, Lagos, Nigeria.": "Diese Website wird betrieben von <strong>EL-ROI Shipping Services</strong>, Ripshorster Str. 379, 45357 Essen, Deutschland (der „Verantwortliche“ im Sinne der Datenschutz-Grundverordnung, DSGVO). Wir haben außerdem ein Büro in Olodi Apapa, Lagos, Nigeria.",
"Questions about your data: <a href=\"mailto:El_roi4ushippingservices@yahoo.com\">El_roi4ushippingservices@yahoo.com</a> or <a href=\"tel:+4915219521826\">+49 1521 9521826</a>.": "Fragen zu Ihren Daten: <a href=\"mailto:El_roi4ushippingservices@yahoo.com\">El_roi4ushippingservices@yahoo.com</a> oder <a href=\"tel:+4915219521826\">+49 1521 9521826</a>.",
"We only collect what you choose to send us:": "Wir erheben nur, was Sie uns selbst senden:",
"<strong>Quote, booking and contact forms:</strong> name, company or private name, phone number, email, address, pickup location, destination, cargo type, weight, number of packages, shipping method, vehicle document or Form M reference, and any message you write.": "<strong>Angebots-, Buchungs- und Kontaktformulare:</strong> Name, Firmen- oder Privatname, Telefonnummer, E-Mail, Adresse, Abholort, Ziel, Frachtart, Gewicht, Anzahl der Packstücke, Versandart, Fahrzeugpapiere oder Form-M-Referenz sowie Ihre Nachricht.",
"<strong>Uploaded documents</strong> (booking form): cargo or shipping documents you attach.": "<strong>Hochgeladene Dokumente</strong> (Buchungsformular): Fracht- oder Versanddokumente, die Sie anhängen.",
"<strong>WhatsApp, phone and email:</strong> whatever you send us through those channels.": "<strong>WhatsApp, Telefon und E-Mail:</strong> alles, was Sie uns über diese Kanäle senden.",
"We do not use analytics, advertising trackers or tracking cookies, and we never ask for bank details, passwords or payment credentials through this website.": "Wir nutzen keine Analyse-Tools, Werbetracker oder Tracking-Cookies und fragen über diese Website niemals Bankdaten, Passwörter oder Zahlungsdaten ab.",
"To prepare quotes, handle bookings and answer your questions (GDPR Art. 6(1)(b): steps before and performance of a contract).": "Um Angebote zu erstellen, Buchungen abzuwickeln und Ihre Fragen zu beantworten (Art. 6 Abs. 1 lit. b DSGVO: vorvertragliche Maßnahmen und Vertragserfüllung).",
"To arrange shipping documents and customs declarations, and to keep records required by law (Art. 6(1)(c): legal obligation).": "Um Versanddokumente und Zollerklärungen zu erstellen und gesetzlich vorgeschriebene Unterlagen aufzubewahren (Art. 6 Abs. 1 lit. c DSGVO: rechtliche Verpflichtung).",
"To keep in touch about a shipment you asked us about (Art. 6(1)(f): our legitimate interest in running our business).": "Um Sie zu einer angefragten Sendung zu kontaktieren (Art. 6 Abs. 1 lit. f DSGVO: unser berechtigtes Interesse am Betrieb unseres Unternehmens).",
"We do not sell your data or use it for advertising.": "Wir verkaufen Ihre Daten nicht und nutzen sie nicht für Werbung.",
"Only where needed to run the website or move your cargo:": "Nur soweit es für den Betrieb der Website oder den Transport Ihrer Fracht nötig ist:",
"<strong>Formspree</strong> (USA): receives form submissions and forwards them to our email.": "<strong>Formspree</strong> (USA): empfängt Formulareingaben und leitet sie an unsere E-Mail weiter.",
"<strong>WhatsApp / Meta</strong>: if you contact us on WhatsApp or a form opens WhatsApp for you.": "<strong>WhatsApp / Meta</strong>: wenn Sie uns per WhatsApp kontaktieren oder ein Formular WhatsApp für Sie öffnet.",
"<strong>GitHub Pages</strong> (hosting): processes technical data such as your IP address to deliver the site.": "<strong>GitHub Pages</strong> (Hosting): verarbeitet technische Daten wie Ihre IP-Adresse, um die Website auszuliefern.",
"<strong>Google</strong>: the office maps (Google Maps) load from Google servers, which receive your IP address. Our website fonts are hosted on our own site, so no data goes to Google for them. The maps load when you scroll to them, so visitors can see where our offices are (Art. 6(1)(f): our legitimate interest in showing our location). You can use the “Open in Google Maps” link instead if you prefer.": "<strong>Google</strong>: Die Standortkarten (Google Maps) werden von Google-Servern geladen, die dabei Ihre IP-Adresse erhalten. Unsere Schriften liegen auf unserer eigenen Website, dafür gehen keine Daten an Google. Die Karten werden geladen, wenn Sie zu ihnen scrollen, damit Besucher sehen, wo unsere Büros sind (Art. 6 Abs. 1 lit. f DSGVO: unser berechtigtes Interesse, unseren Standort zu zeigen). Alternativ können Sie den Link „In Google Maps öffnen“ nutzen.",
"<strong>Shipping partners, ports and customs authorities</strong>: the details needed to ship your cargo.": "<strong>Versandpartner, Häfen und Zollbehörden</strong>: die für den Versand Ihrer Fracht nötigen Angaben.",
"Some of these providers are outside the EU. Where that is the case, transfers rely on safeguards such as the EU–US Data Privacy Framework or the European Commission’s standard contractual clauses.": "Einige dieser Anbieter sitzen außerhalb der EU. In diesen Fällen stützt sich die Übermittlung auf Garantien wie das EU-US Data Privacy Framework oder die Standardvertragsklauseln der Europäischen Kommission.",
"Enquiries that do not lead to a shipment are deleted within 12 months. Records of shipments and invoices are kept for as long as German commercial and tax law requires (usually 6 to 10 years), then deleted.": "Anfragen, aus denen keine Sendung wird, löschen wir innerhalb von 12 Monaten. Unterlagen zu Sendungen und Rechnungen bewahren wir so lange auf, wie es das deutsche Handels- und Steuerrecht verlangt (in der Regel 6 bis 10 Jahre), und löschen sie dann.",
"You can ask us to show you, correct, delete or restrict the data we hold about you, to object to its use, or to receive it in a portable format. Where we rely on your consent, you can withdraw it at any time. Just email <a href=\"mailto:El_roi4ushippingservices@yahoo.com\">El_roi4ushippingservices@yahoo.com</a>.": "Sie können Auskunft über Ihre Daten verlangen, sie berichtigen, löschen oder einschränken lassen, der Nutzung widersprechen oder sie in einem übertragbaren Format erhalten. Eine erteilte Einwilligung können Sie jederzeit widerrufen. Schreiben Sie einfach an <a href=\"mailto:El_roi4ushippingservices@yahoo.com\">El_roi4ushippingservices@yahoo.com</a>.",
"You can also complain to a data protection authority, for example the one responsible for us: Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen (LDI NRW), Düsseldorf. Customers in Nigeria can contact the Nigeria Data Protection Commission (NDPC).": "Sie können sich außerdem bei einer Datenschutzaufsichtsbehörde beschweren, zum Beispiel bei der für uns zuständigen: Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen (LDI NRW), Düsseldorf. Kunden in Nigeria können sich an die Nigeria Data Protection Commission (NDPC) wenden.",
"This website does not set cookies of its own. Google may set its own cookies through the office maps.": "Diese Website setzt keine eigenen Cookies. Google kann über die Standortkarten eigene Cookies setzen.",
"We may update this policy when our services or the law change. The date below shows the latest version.": "Wir passen diese Erklärung an, wenn sich unsere Leistungen oder die Rechtslage ändern. Das Datum unten zeigt den aktuellen Stand.",
"Last updated: 26 September 2026": "Stand: 26. September 2026",
# ---- quote ----
"Get a Free Shipping Quote from Germany | EL-ROI Shipping": "Kostenloses Versandangebot ab Deutschland | EL-ROI Shipping",
"Request a transparent, no-pressure sea freight quote from Germany for vehicles, containers, machinery or general cargo. No hidden fees.": "Fordern Sie ein transparentes, unverbindliches Seefracht-Angebot ab Deutschland für Fahrzeuge, Container, Maschinen oder Stückgut an. Keine versteckten Gebühren.",
"Get a quote": "Angebot anfordern",
"Request a <em>shipping quotation</em>": "Fordern Sie ein <em>Versandangebot</em> an",
"Tell us about your cargo and we'll get back to you with a transparent, no-pressure estimate.": "Beschreiben Sie uns Ihre Fracht, und Sie erhalten eine transparente, unverbindliche Kostenschätzung.",
"Your shipment": "Ihre Sendung",
"Company name": "Firmenname",
"Address": "Adresse",
"Include Form M reference if your cargo needs a special declaration.": "Geben Sie die Form-M-Referenz an, wenn Ihre Fracht eine Sondererklärung benötigt.",
"Additional details": "Weitere Angaben",
"Want a rough figure first? Try the <a href=\"calculator.html\">shipping calculator</a>. How we use your details: <a href=\"privacy.html\">Privacy Policy</a>. Bookings are subject to our <a href=\"terms.html\">Terms & Conditions</a>.": "Erst eine grobe Zahl? Probieren Sie den <a href=\"calculator.html\">Kostenrechner</a>. Wie wir Ihre Angaben nutzen: <a href=\"privacy.html\">Datenschutzerklärung</a>. Für Buchungen gelten unsere <a href=\"terms.html\">AGB</a>.",
"Request Quote §": "Angebot anfordern §",
"Hello EL-ROI, I'd like a shipping quote:": "Hallo EL-ROI, ich möchte ein Versandangebot:",
"e.g. Essen, Germany": "z. B. Essen, Deutschland",
"e.g. Antwerp, Belgium": "z. B. Antwerpen, Belgien",
"Make and model, dimensions, weight, number of items...": "Marke und Modell, Maße, Gewicht, Anzahl der Teile ...",
"Get a Free Shipping Quote from Germany": "Kostenloses Versandangebot ab Deutschland",
# ---- routes ----
"Shipping Routes from Germany: Europe, Lagos & Worldwide | EL-ROI": "Versandrouten ab Deutschland: Europa, Lagos & weltweit | EL-ROI",
"Sea freight from Essen, Germany: major routes to Belgium, Austria and Holland, plus Lagos, Nigeria and any port worldwide. Around two weeks after loading.": "Seefracht ab Essen: Hauptrouten nach Belgien, Österreich und in die Niederlande, dazu Lagos, Nigeria und jeder Hafen weltweit. Rund zwei Wochen nach der Verladung.",
"Where we ship": "Wohin wir versenden",
"Germany to <em>any part of the world</em>": "Von Deutschland <em>in jeden Teil der Welt</em>",
"Major routes from our Essen headquarters to Belgium, Austria and Holland, and sea freight to any part of the world, including Lagos, home of our second office.": "Hauptrouten von unserem Sitz in Essen nach Belgien, Österreich und in die Niederlande, und Seefracht in jeden Teil der Welt, auch nach Lagos, wo unser zweites Büro sitzt.",
"Coverage": "Abdeckung",
"Our <em>shipping routes</em>": "Unsere <em>Versandrouten</em>",
"Every route runs by sea freight from Essen, Germany.": "Jede Route läuft per Seefracht ab Essen.",
"<i class=\"eu\"></i>Lagos office": "<i class=\"eu\"></i>Büro Lagos",
"<i class=\"ww\"></i>Worldwide": "<i class=\"ww\"></i>Weltweit",
"The network": "Das Netzwerk",
"One hub, <em>every port</em>": "Ein Standort, <em>jeder Hafen</em>",
"Essen → Europe": "Essen → Europa",
"Our major routes: Belgium, Austria and Holland. Around two weeks after loading.": "Unsere Hauptrouten: Belgien, Österreich und die Niederlande. Rund zwei Wochen nach der Verladung.",
"Essen → Any part of the world": "Essen → jeder Teil der Welt",
"Sea freight to Africa, the Americas, the Middle East and Asia. Transit varies by destination, so ask us for a route-specific timeline.": "Seefracht nach Afrika, Amerika, in den Nahen Osten und nach Asien. Die Laufzeit hängt vom Ziel ab, fragen Sie uns nach Ihrer Route.",
"Our second office in Olodi Apapa, Lagos, supports shipments arriving in Nigeria.": "Unser zweites Büro in Olodi Apapa, Lagos, betreut Sendungen, die in Nigeria ankommen.",
"Not sure if we cover <em>your destination?</em>": "Nicht sicher, ob wir <em>Ihr Ziel anfahren?</em>",
"We ship from Germany to any part of the world. Reach out and we'll confirm the route for you.": "Wir versenden von Deutschland in jeden Teil der Welt. Melden Sie sich, und wir bestätigen Ihnen die Route.",
"Contact Us §": "Kontakt aufnehmen §",
"Shipping Routes from Germany": "Versandrouten ab Deutschland",
# ---- services ----
"Car, Truck, Tractor & Container Shipping from Germany | EL-ROI Shipping": "Auto-, Lkw-, Traktor- & Containerversand ab Deutschland | EL-ROI",
"Ship vehicles, trucks, tractors, 20ft and 40ft containers, machinery, fragile goods and documents by sea from Germany, with documents and Form M handled.": "Verschiffen Sie Fahrzeuge, Lkw, Traktoren, 20- und 40-Fuß-Container, Maschinen, zerbrechliche Güter und Dokumente per Seefracht ab Deutschland, inklusive Papieren und Form M.",
"What we offer": "Unsere Leistungen",
"Freight services <em>built around your cargo</em>": "Frachtservice, <em>ganz auf Ihre Fracht zugeschnitten</em>",
"Sea freight from Germany for everything from documents to heavy machinery, with the paperwork handled and the price agreed up front.": "Seefracht ab Deutschland für alles vom Dokument bis zur schweren Maschine, mit erledigten Papieren und vorab vereinbartem Preis.",
"Cargo gallery": "Frachtübersicht",
"What <em>we move</em>": "Was <em>wir bewegen</em>",
"From single documents to full oversized machinery, we handle it with the same standard of care.": "Vom einzelnen Dokument bis zur übergroßen Maschine: Alles erhält dieselbe Sorgfalt.",
"Vehicles & vehicle parts": "Fahrzeuge & Fahrzeugteile",
"Cars, trucks and vehicle parts shipped with full documentation support. We make sure the vehicle papers are in order before anything is loaded. Shipping a car to Nigeria? Read our <a class=\"inline-link\" href=\"guide-ship-car-germany-to-nigeria.html\">step-by-step guide</a>.": "Autos, Lkw und Fahrzeugteile, verschifft mit vollständiger Unterstützung bei den Papieren. Wir sorgen dafür, dass die Fahrzeugpapiere stimmen, bevor verladen wird. Auto nach Nigeria? Lesen Sie unseren <a class=\"inline-link\" href=\"guide-ship-car-germany-to-nigeria.html\">Schritt-für-Schritt-Ratgeber (Englisch)</a>.",
"Vehicles and spare parts": "Fahrzeuge und Ersatzteile",
"Vehicle documentation handled correctly": "Fahrzeugpapiere korrekt erledigt",
"Form M special declarations where required": "Form-M-Sondererklärungen, wo nötig",
"Tractors and agricultural equipment, prepared and secured for sea freight to any part of the world.": "Traktoren und landwirtschaftliche Geräte, vorbereitet und gesichert für die Seefracht in jeden Teil der Welt.",
"Tractors and implements": "Traktoren und Anbaugeräte",
"Secured for sea freight": "Gesichert für die Seefracht",
"Transparent estimate before booking": "Transparente Kostenschätzung vor der Buchung",
"Tractor heads, trucks and commercial vehicles exported directly from Germany.": "Zugmaschinen, Lkw und Nutzfahrzeuge, direkt aus Deutschland exportiert.",
"Trucks and tractor units": "Lkw und Sattelzugmaschinen",
"Shipped direct from Germany": "Direkt aus Deutschland verschifft",
"Clear communication at every step": "Klare Kommunikation bei jedem Schritt",
"Containers (20FT / 40FT)": "Container (20 / 40 Fuß)",
"Full container loads, packed, sealed and shipped by sea freight to destinations worldwide.": "Komplette Containerladungen, gepackt, versiegelt und per Seefracht zu Zielen weltweit verschifft.",
"20FT and 40FT HC containers": "20-Fuß- und 40-Fuß-HC-Container",
"Packed and secured for the voyage": "Gepackt und gesichert für die Reise",
"Sea freight to any part of the world": "Seefracht in jeden Teil der Welt",
"Oversized & heavy cargo": "Übergroße & schwere Fracht",
"Trailers, construction equipment and oversized loads, planned around real constraints.": "Auflieger, Baumaschinen und übergroße Ladungen, geplant nach den tatsächlichen Gegebenheiten.",
"Trailers and chassis": "Auflieger und Chassis",
"Construction equipment": "Baumaschinen",
"Engines and industrial machinery": "Motoren und Industriemaschinen",
"Also on board": "Außerdem an Bord",
"Every cargo, <em>the same care</em>": "Jede Fracht, <em>dieselbe Sorgfalt</em>",
"Packed, documented and shipped with full care from pickup to port.": "Verpackt, dokumentiert und mit voller Sorgfalt von der Abholung bis zum Hafen verschifft.",
"Full and part container loads, sea freight to destinations worldwide.": "Voll- und Teilcontainerladungen, Seefracht zu Zielen weltweit.",
"Machinery & equipment": "Maschinen & Ausrüstung",
"Engines and industrial machinery shipped with proper securing and paperwork.": "Motoren und Industriemaschinen, sachgerecht gesichert und mit korrekten Papieren verschifft.",
"Extra-care packaging and handling for delicate or high-value items.": "Besonders sorgfältige Verpackung und Behandlung für empfindliche oder wertvolle Güter.",
"Important papers shipped safely alongside, or independent of, your cargo.": "Wichtige Unterlagen, sicher mit Ihrer Fracht oder unabhängig davon verschickt.",
"Not listed?": "Nicht dabei?",
"Ask us about your cargo": "Fragen Sie uns nach Ihrer Fracht",
"Get in touch and we'll confirm whether we can move it, and what it takes.": "Melden Sie sich, und wir sagen Ihnen, ob und wie wir sie transportieren können.",
"Contact us §": "Kontakt aufnehmen §",
"Shipping method": "Versandart",
"Sea freight, <em>done right</em>": "Seefracht, <em>richtig gemacht</em>",
"All shipments move by sea freight. Delivery time depends on the destination country, but averages around two weeks after your container is loaded onto the ship.": "Alle Sendungen reisen per Seefracht. Die Laufzeit hängt vom Zielland ab, liegt aber im Schnitt bei rund zwei Wochen, nachdem Ihr Container auf das Schiff verladen wurde.",
"What we need from you": "Was wir von Ihnen brauchen",
"Your checklist": "Ihre Checkliste",
"Name and address": "Name und Adresse",
"Vehicle documentation": "Fahrzeugpapiere",
"Special declaration paperwork (Form M), where applicable": "Unterlagen für Sondererklärungen (Form M), falls zutreffend",
"Full checklist §": "Vollständige Checkliste (Englisch) §",
"Restrictions": "Einschränkungen",
"What we don't accept": "Was wir nicht annehmen",
"Certain cargo types are restricted for safety and regulatory reasons. Get in touch to confirm your cargo qualifies before booking.": "Bestimmte Frachtarten sind aus Sicherheits- oder rechtlichen Gründen eingeschränkt. Klären Sie vor der Buchung mit uns, ob Ihre Fracht in Frage kommt.",
"Car, Truck, Tractor & Container Shipping from Germany": "Auto-, Lkw-, Traktor- & Containerversand ab Deutschland",
# ---- terms ----
"Terms & Conditions | EL-ROI Shipping Services": "Allgemeine Geschäftsbedingungen | EL-ROI Shipping Services",
"Terms & Conditions": "AGB",
"Terms & <em>conditions</em>": "Allgemeine <em>Geschäftsbedingungen</em>",
"The terms that apply to our quotes, bookings and shipping services.": "Die Bedingungen, die für unsere Angebote, Buchungen und Versandleistungen gelten.",
"Terms and conditions for quotes, bookings and freight forwarding services by EL-ROI Shipping Services.": "Allgemeine Geschäftsbedingungen für Angebote, Buchungen und Speditionsleistungen von EL-ROI Shipping Services.",
"Scope": "Geltungsbereich",
"Quotes and estimates": "Angebote und Kostenschätzungen",
"Bookings": "Buchungen",
"Your responsibilities": "Ihre Pflichten",
"Prices and payment": "Preise und Zahlung",
"Transit times": "Laufzeiten",
"Liability and insurance": "Haftung und Versicherung",
"Damage and claims": "Schäden und Reklamationen",
"Cancellations": "Stornierungen",
"Using this website": "Nutzung dieser Website",
"Law and jurisdiction": "Recht und Gerichtsstand",
"These terms apply to all quotes, bookings and freight forwarding services provided by <strong>EL-ROI Shipping Services</strong>, Ripshorster Str. 379, 45357 Essen, Germany (“we”, “us”), and to the use of this website. Anything we agree with you individually in writing takes priority over these terms.": "Diese Bedingungen gelten für alle Angebote, Buchungen und Speditionsleistungen von <strong>EL-ROI Shipping Services</strong>, Ripshorster Str. 379, 45357 Essen („wir“, „uns“), sowie für die Nutzung dieser Website. Individuelle schriftliche Vereinbarungen haben Vorrang vor diesen Bedingungen.",
"Where we agree it with business customers, our services are also carried out under the German Freight Forwarders’ Standard Terms and Conditions (ADSp 2017). Mandatory law always applies, including the German Commercial Code (HGB) and international transport conventions.": "Soweit mit Geschäftskunden vereinbart, erbringen wir unsere Leistungen zusätzlich auf Grundlage der Allgemeinen Deutschen Spediteurbedingungen (ADSp 2017). Zwingendes Recht gilt immer, einschließlich des Handelsgesetzbuchs (HGB) und internationaler Transportübereinkommen.",
"A quote is based on the information you give us (cargo type, dimensions, weight, pickup point and destination). If that information turns out to be different, the price may change, and we will tell you before going ahead.": "Ein Angebot beruht auf Ihren Angaben (Frachtart, Maße, Gewicht, Abholort und Ziel). Weichen diese ab, kann sich der Preis ändern. Darüber informieren wir Sie, bevor wir fortfahren.",
"The online shipping calculator gives a rough, non-binding estimate only.": "Der Online-Kostenrechner liefert nur eine grobe, unverbindliche Schätzung.",
"Unless stated otherwise, quotes do not include customs duties, import taxes, port and terminal charges at destination, storage, inspections or fees charged by authorities.": "Sofern nicht anders angegeben, enthalten Angebote keine Zölle, Einfuhrsteuern, Hafen- und Terminalgebühren am Zielort, Lagerkosten, Beschauen oder behördlichen Gebühren.",
"Quotes are valid for the period stated on them, or 14 days if no period is given, because freight rates change.": "Angebote gelten für den darauf genannten Zeitraum oder, wenn keiner genannt ist, 14 Tage, da sich Frachtraten ändern.",
"Sending a booking or quote request through the website, WhatsApp, phone or email does not create a contract. A contract is formed only when we confirm your booking in writing (email or WhatsApp is fine) and you accept the price.": "Eine Buchungs- oder Angebotsanfrage über die Website, WhatsApp, Telefon oder E-Mail begründet noch keinen Vertrag. Ein Vertrag kommt erst zustande, wenn wir Ihre Buchung schriftlich bestätigen (E-Mail oder WhatsApp genügt) und Sie den Preis annehmen.",
"Give us complete and correct details about the cargo, the sender and the receiver.": "Machen Sie vollständige und richtige Angaben zur Fracht, zum Absender und zum Empfänger.",
"Provide the documents needed for export and import on time, including vehicle documents and, where required, the Form M special declaration.": "Stellen Sie die für Export und Import nötigen Dokumente rechtzeitig bereit, einschließlich Fahrzeugpapieren und, falls erforderlich, der Sondererklärung Form M.",
"Make sure the cargo is legal to export and import, and properly packed, secured and labelled unless we have agreed to do this.": "Stellen Sie sicher, dass die Fracht rechtmäßig aus- und eingeführt werden darf und ordnungsgemäß verpackt, gesichert und gekennzeichnet ist, sofern nicht wir dies übernehmen.",
"Remove fuel, batteries, gas bottles and personal belongings from vehicles unless we have agreed otherwise in writing.": "Entfernen Sie Kraftstoff, Batterien, Gasflaschen und persönliche Gegenstände aus Fahrzeugen, sofern nicht schriftlich anders vereinbart.",
"Do not hand us dangerous, illegal or restricted goods without telling us first. Ask us before booking if you are unsure whether your cargo qualifies.": "Übergeben Sie uns keine gefährlichen, illegalen oder eingeschränkten Güter, ohne uns vorher zu informieren. Fragen Sie vor der Buchung, wenn Sie unsicher sind.",
"You are responsible for costs, delays, fines or damage caused by missing or incorrect information or documents.": "Für Kosten, Verzögerungen, Bußgelder oder Schäden durch fehlende oder falsche Angaben oder Dokumente sind Sie verantwortlich.",
"Payment terms are agreed with you directly and shown on our invoice. We never ask for bank details or payment credentials through this website.": "Zahlungsbedingungen vereinbaren wir direkt mit Ihnen, sie stehen auf unserer Rechnung. Über diese Website fragen wir niemals Bank- oder Zahlungsdaten ab.",
"Unless agreed otherwise, freight charges are due before the cargo is loaded or released.": "Sofern nicht anders vereinbart, sind Frachtkosten vor der Verladung bzw. Freigabe der Fracht fällig.",
"Customs duties, taxes and destination charges are payable by you (or the receiver), even if they arise after shipping.": "Zölle, Steuern und Kosten am Zielort tragen Sie (bzw. der Empfänger), auch wenn sie nach dem Versand anfallen.",
"We may hold the cargo or its documents until outstanding amounts for that shipment have been paid, as the law allows.": "Wir können die Fracht oder ihre Dokumente im gesetzlich zulässigen Rahmen zurückhalten, bis offene Beträge für diese Sendung bezahlt sind.",
"Transit times are estimates. Sea freight usually takes around two weeks after the container is loaded, but this depends on the destination, the shipping line, port congestion, weather and customs. We are not responsible for delays caused by carriers, authorities or events beyond our control, and we will keep you informed.": "Laufzeiten sind Schätzungen. Seefracht dauert meist rund zwei Wochen nach der Verladung des Containers, abhängig von Ziel, Reederei, Hafenauslastung, Wetter und Zoll. Für Verzögerungen durch Frachtführer, Behörden oder Ereignisse außerhalb unseres Einflusses sind wir nicht verantwortlich. Wir halten Sie auf dem Laufenden.",
"Our liability for loss of or damage to cargo is limited to the amounts set by mandatory law (such as the HGB) and the international conventions that apply to the transport, and, where agreed, by the ADSp.": "Unsere Haftung für Verlust oder Beschädigung der Fracht ist auf die Beträge begrenzt, die zwingendes Recht (etwa das HGB), die für den Transport geltenden internationalen Übereinkommen und, soweit vereinbart, die ADSp vorsehen.",
"These limits do not apply where damage is caused intentionally or through gross negligence, or where the law does not allow a limit.": "Diese Grenzen gelten nicht bei Vorsatz oder grober Fahrlässigkeit oder wenn das Gesetz keine Begrenzung zulässt.",
"We are not liable for loss caused by incorrect information, poor packing by the sender, the nature of the goods, or acts of authorities.": "Wir haften nicht für Schäden durch falsche Angaben, mangelhafte Verpackung durch den Absender, die Beschaffenheit der Güter oder behördliche Maßnahmen.",
"Standard liability limits can be lower than the value of your cargo. We strongly recommend cargo insurance, and we can arrange it on request.": "Die gesetzlichen Haftungsgrenzen können unter dem Wert Ihrer Fracht liegen. Wir empfehlen dringend eine Transportversicherung, die wir auf Wunsch vermitteln.",
"Please check the cargo on delivery. Visible loss or damage must be noted on the delivery documents and reported to us immediately. Hidden damage must be reported in writing within 7 days of delivery. Late reports can make it impossible to claim against the carrier.": "Bitte prüfen Sie die Fracht bei Ablieferung. Äußerlich erkennbare Verluste oder Schäden müssen auf den Ablieferpapieren vermerkt und uns sofort gemeldet werden. Äußerlich nicht erkennbare Schäden sind innerhalb von 7 Tagen nach Ablieferung schriftlich anzuzeigen. Verspätete Meldungen können Ansprüche gegen den Frachtführer ausschließen.",
"You can cancel a booking free of charge until we have made arrangements for it. After that, you pay the costs we have already incurred (for example container booking, collection, storage or documents). Once the cargo has been loaded onto the ship, the full freight charge is due.": "Sie können eine Buchung kostenlos stornieren, solange wir noch keine Vorkehrungen dafür getroffen haben. Danach tragen Sie die bereits entstandenen Kosten (z. B. Containerbuchung, Abholung, Lagerung oder Dokumente). Ist die Fracht auf das Schiff verladen, ist die volle Fracht fällig.",
"The information on this website is general and may change. Photos show examples of our work. All content belongs to EL-ROI Shipping Services and may not be copied without permission. How we handle your personal data is explained in our <a href=\"privacy.html\">Privacy Policy</a>.": "Die Informationen auf dieser Website sind allgemein und können sich ändern. Die Fotos zeigen Beispiele unserer Arbeit. Alle Inhalte gehören EL-ROI Shipping Services und dürfen nicht ohne Erlaubnis kopiert werden. Wie wir mit Ihren Daten umgehen, erklärt unsere <a href=\"privacy.html\">Datenschutzerklärung</a>.",
"These terms are governed by German law. For business customers, the place of jurisdiction is Essen, Germany. Consumers keep any protections they have under the law of the country where they live. If any part of these terms is invalid, the rest remains in force.": "Es gilt deutsches Recht. Gerichtsstand für Geschäftskunden ist Essen. Verbraucher behalten den Schutz, den ihnen das Recht ihres Wohnsitzlandes gewährt. Sollte eine Bestimmung unwirksam sein, bleiben die übrigen wirksam.",
"Questions: <a href=\"mailto:El_roi4ushippingservices@yahoo.com\">El_roi4ushippingservices@yahoo.com</a> · <a href=\"tel:+4915219521826\">+49 1521 9521826</a><br/>Last updated: 26 September 2026": "Fragen: <a href=\"mailto:El_roi4ushippingservices@yahoo.com\">El_roi4ushippingservices@yahoo.com</a> · <a href=\"tel:+4915219521826\">+49 1521 9521826</a><br/>Stand: 26. September 2026",
}

# ---- consent ----
DE.update({
"Cookie settings": "Cookie-Einstellungen",
"Privacy settings": "Datenschutz-Einstellungen",
"This website sets no cookies of its own. Our office maps come from Google Maps, which can set cookies and receives your IP address. Allow the maps? You can change this any time under “Cookie settings” at the bottom of the page. <a href=\"privacy.html#cookies\">Privacy Policy</a>": "Diese Website setzt keine eigenen Cookies. Unsere Standortkarten stammen von Google Maps, das Cookies setzen kann und Ihre IP-Adresse erhält. Karten erlauben? Sie können das jederzeit unter „Cookie-Einstellungen“ unten auf der Seite ändern. <a href=\"privacy.html#cookies\">Datenschutzerklärung</a>",
"Decline": "Ablehnen",
"Accept": "Akzeptieren",
"Accept and show map": "Akzeptieren und Karte anzeigen",
"The map is provided by Google, which can set cookies and receives your IP address. See our <a href=\"privacy.html#share\">Privacy Policy</a>.": "Die Karte stammt von Google, das Cookies setzen kann und Ihre IP-Adresse erhält. Siehe unsere <a href=\"privacy.html#share\">Datenschutzerklärung</a>.",
"Ripshorster Str. 379, 45357 Essen": "Ripshorster Str. 379, 45357 Essen",
"<a href=\"privacy.html\">Privacy Policy</a> · <a href=\"terms.html\">Terms & Conditions</a> · <button class=\"linklike\" data-consent-open=\"\" type=\"button\">Cookie settings</button> · <em>Your satisfaction, our priority.</em>": "<a href=\"privacy.html\">Datenschutz</a> · <a href=\"terms.html\">AGB</a> · <button class=\"linklike\" data-consent-open=\"\" type=\"button\">Cookie-Einstellungen</button> · <em>Ihre Zufriedenheit ist unsere Priorität.</em>",
"<strong>Google</strong>: the office maps (Google Maps) load from Google servers, which receive your IP address. Our website fonts are hosted on our own site, so no data goes to Google for them. The maps only load after you agree in our privacy settings (Art. 6(1)(a) GDPR and § 25(1) TDDDG: consent). If you decline, you can still use the “Open in Google Maps” link.": "<strong>Google</strong>: Die Standortkarten (Google Maps) werden von Google-Servern geladen, die dabei Ihre IP-Adresse erhalten. Unsere Schriften liegen auf unserer eigenen Website, dafür gehen keine Daten an Google. Die Karten werden erst geladen, wenn Sie in unseren Datenschutz-Einstellungen zustimmen (Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG: Einwilligung). Wenn Sie ablehnen, können Sie weiterhin den Link „In Google Maps öffnen“ nutzen.",
"This website does not set cookies of its own. When you first visit, we ask whether you allow the Google Maps office maps, which can set Google cookies. Your choice is saved in your browser’s local storage (never sent to us) so we don’t ask again. You can change or withdraw it at any time with “Cookie settings” at the bottom of every page.": "Diese Website setzt keine eigenen Cookies. Beim ersten Besuch fragen wir, ob Sie die Standortkarten von Google Maps erlauben, die Google-Cookies setzen können. Ihre Entscheidung wird im lokalen Speicher Ihres Browsers gespeichert (nie an uns übertragen), damit wir nicht erneut fragen. Sie können sie jederzeit über „Cookie-Einstellungen“ unten auf jeder Seite ändern oder widerrufen.",
})

# Strings that stay the same in German (names, numbers, addresses)
SAME = """Ripshorster Str. 379, Essen|Olodi Apapa, Lagos|+49 1521 9521826|WhatsApp|EL-ROI <em>Shipping</em>|EN|DE|El_roi4ushippingservices@yahoo.com|1999|Olodi Apapa, Lagos, Nigeria|Iyamah|EL-ROI Shipping|EL-ROI Shipping Services Lagos|02|KG|Lagos, Nigeria|—|§+49 1521 9521826|§El_roi4ushippingservices@yahoo.com|Olodi Apapa<br/>Lagos, Nigeria|Volvo FH|John Deere 3140|20|+|2|(01)|(02)|(03)|(04)|(05)|(06)|01|03|04|05|Essen|EU|WW|NG|§ WhatsApp|Cookies|Vision|Mission|Fairness.|FAQ""".split('|')
